#pragma once

#define HAPSpecificCodecGroup           "HAPSpecificCodecGroup"
#define HAPChunkCount                   "HAPChunkCount"

#define HAP_VIDEOFILETYPE				'hap'
#define HAP_VIDEOFILEEXT				L"mov"
#define HAP_FILE_NAME					L"HAP"
#define HAP_VIDEO_FILE_NAME				L"HAP Video"
#define	HAP_VIDEOCLSS					'HAPY'
#define EXPORTER_NAME					"HAP Exporter"
#define SETTING_STRING					"Turn on marker export and warnings? (Don't turn this on for rendering preview files)"
#define TOP_VIDEO_PARAM_GROUP_NAME		L"Video parameters"
#define VIDEO_CODEC_PARAM_GROUP_NAME	L"Video"
#define BASIC_VIDEO_PARAM_GROUP_NAME	L"Basic video"
#define CODEC_SPECIFIC_PARAM_GROUP_NAME L"Advanced video"
#define STR_CODEC						L"Codec"
#define STR_CODEC_TOOLTIP				L"The video codec to be used for encode."
#define STR_WIDTH						L"Width"
#define STR_HEIGHT						L"Height"
#define STR_FRAME_RATE					L"Frame Rate (fps)"
#define STR_FRAME_RATE_10				L"10"
#define STR_FRAME_RATE_15				L"15"
#define STR_FRAME_RATE_23976			L"23.976"
#define STR_FRAME_RATE_24				L"24"
#define STR_FRAME_RATE_25				L"25 (PAL)"
#define STR_FRAME_RATE_2997				L"29.97 (NTSC)"
#define STR_FRAME_RATE_30				L"30"
#define STR_FRAME_RATE_50				L"50"
#define STR_FRAME_RATE_5994				L"59.94"
#define STR_FRAME_RATE_60				L"60"

#define TOP_AUDIO_PARAM_GROUP_NAME      L"Audio parameters"
#define BASIC_AUDIO_PARAM_GROUP_NAME    L"Basic Audio Setings"
#define STR_SAMPLE_RATE                 L"Sample Rate"
#define STR_SAMPLE_RATE_8               L"8000 Hz"
#define STR_SAMPLE_RATE_16              L"16000 Hz"
#define STR_SAMPLE_RATE_32              L"32000 Hz"
#define STR_SAMPLE_RATE_441             L"44100 Hz"
#define STR_SAMPLE_RATE_48              L"48000 Hz"
#define STR_SAMPLE_RATE_96              L"96000 Hz"
#define STR_CHANNEL_TYPE                L"Channels"
#define STR_CHANNEL_TYPE_MONO           L"Mono"
#define STR_CHANNEL_TYPE_STEREO         L"Stereo"
#define STR_CHANNEL_TYPE_51             L"5.1"
