#pragma once

#define HAPSpecificCodecGroup           "HAPSpecificCodecGroup"
#define HAPChunkCount                   "HAPChunkCount"

#define HAP_VIDEOFILETYPE				'hap'
#define HAP_VIDEOFILEEXT				L"mov"
#define HAP_FILE_NAME					L"HAP"
#define HAP_VIDEO_FILE_NAME				L"HAP Video"
#define	HAP_VIDEOCLSS					'HAPY'
#define EXPORTER_NAME					"HAP Exporter"
#define SETTING_STRING					"Turn on marker export and warnings? (Don't turn this on for rendering preview files)"
#define TOP_VIDEO_PARAM_GROUP_NAME		L"Video parameters"
#define VIDEO_CODEC_PARAM_GROUP_NAME	L"Video"
#define BASIC_VIDEO_PARAM_GROUP_NAME	L"Basic video"
#define CODEC_SPECIFIC_PARAM_GROUP_NAME L"Advanced video"
#define BASIC_AUDIO_PARAM_GROUP_NAME	L"Basic audio"
#define STR_CODEC						L"Codec"
#define STR_CODEC_TOOLTIP				L"The video codec to be used for encode."
#define STR_WIDTH						L"Width"
#define STR_HEIGHT						L"Height"
#define STR_FRAME_RATE					L"Frame Rate (fps)"
#define STR_FRAME_RATE_10				L"10"
#define STR_FRAME_RATE_15				L"15"
#define STR_FRAME_RATE_23976			L"23.976"
#define STR_FRAME_RATE_24				L"24"
#define STR_FRAME_RATE_25				L"25 (PAL)"
#define STR_FRAME_RATE_2997				L"29.97 (NTSC)"
#define STR_FRAME_RATE_30				L"30"
#define STR_FRAME_RATE_50				L"50"
#define STR_FRAME_RATE_5994				L"59.94"
#define STR_FRAME_RATE_60				L"60"
#define STR_HAP_SUBCODEC                L"Subcodec type"
#define STR_HAP_SUBCODEC_0              L"Hap"
#define STR_HAP_SUBCODEC_1              L"Hap Alpha"
#define STR_HAP_SUBCODEC_2              L"Hap Q"
#define STR_HAP_SUBCODEC_3              L"Hap Q Alpha"
#define STR_HAP_SUBCODEC_4              L"Hap Alpha-Only"
#define STR_HAP_CHUNKING                L"Chunk count"
#define STR_HAP_CHUNKS_AUTO             L"Auto"