#pragma once

#define ADBEStillSequence               "ADBEStillSequence"
#define ADBECompressionLevel            "ADBECompressionLevel"

#define HAP_VIDEOFILETYPE				'hap'
#define HAP_VIDEOFILEEXT				L"mov"
#define HAP_FILE_NAME					L"HAP"
#define HAP_VIDEO_FILE_NAME				L"HAP Video"
#define HAP_8_BIT_NAME  				L"HQ 8-bit (YUVA8)"
#define HAP_10_BIT_NAME					L"HQ 10-bit (YUV10A2)"
#define HAP_10_BIT_RGB_NAME				L"Lossless 10-bit (RGB10A2)"
#define HAP_10_BIT_YUV_NAME				L"HQ 10-bit (YUV10A2)"
#define HAP_10_BIT_RAW_NAME				L"RAW 10-bit (RGB10A2)"
#define HAP_16_BIT_NAME					L"HQ 16-bit (YUVA16)"
#define HAP_8_BIT_RGB_NAME				L"Lossless 8-bit (RGBA8)"
#define HAP_16_BIT_RGB_NAME				L"Lossless 16-bit (RGBA16)"
#define	HAP_NAME						"PREMIERE D3V_FILE "
#define	HAP_VIDEOCLSS					'HAPY'
#define EXPORTER_NAME					"HAP Exporter"
#define SETTING_STRING					"Turn on marker export and warnings? (Don't turn this on for rendering preview files)"
#define TOP_VIDEO_PARAM_GROUP_NAME		L"Video parameters"
#define VIDEO_CODEC_PARAM_GROUP_NAME	L"Video"
#define BASIC_VIDEO_PARAM_GROUP_NAME	L"Basic video"
#define BASIC_AUDIO_PARAM_GROUP_NAME	L"Basic audio"
#define STR_CODEC						L"Codec"
#define STR_CODEC_TOOLTIP				L"The video codec to be used for encode."
#define STR_WIDTH						L"Width"
#define STR_HEIGHT						L"Height"
#define STR_FRAME_RATE					L"Frame Rate (fps)"
#define STR_FRAME_RATE_10				L"10"
#define STR_FRAME_RATE_15				L"15"
#define STR_FRAME_RATE_23976			L"23.976"
#define STR_FRAME_RATE_24				L"24"
#define STR_FRAME_RATE_25				L"25 (PAL)"
#define STR_FRAME_RATE_2997				L"29.97 (NTSC)"
#define STR_FRAME_RATE_30				L"30"
#define STR_FRAME_RATE_50				L"50"
#define STR_FRAME_RATE_5994				L"59.94"
#define STR_FRAME_RATE_60				L"60"
#define STR_HAP_SUBCODEC                L"Subcodec type"
#define STR_HAP_SUBCODEC_0              L"Hap"
#define STR_HAP_SUBCODEC_1              L"Hap Alpha"
#define STR_HAP_SUBCODEC_2              L"Hap Q"
#define STR_HAP_SUBCODEC_3              L"Hap Q Alpha"
#define STR_HAP_SUBCODEC_4              L"Hap Alpha-Only"
